### ISSUE TITLE
calculation math 

### ISSUE THREAD

**Issue by andriysvi** [hjjerrychen/skatecalc#1]
Hey jccool5000,

right now i am doing calculator for school for figure skating. The scoring system is complicated and I do not really get it. is there any way I can see how you calculate the results from a performance.

Regards

**Comment by hjjerrychen** [comment]
Hi, yes is there some way I can contact you?

If you are looking for documentation, it can be found at: https://www.isu.org/figure-skating/rules/fsk-regulations-rules/file (rule 353)
